version: "3.8"
services:
  docker:
    image: docker:dind
    restart: always
    privileged: true
    container_name: docker
    ports:
      - "2376:2376"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_STORAGE_OPTS=--storage-driver overlay2
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
        #     - jenkins-docker-certs-ca:/certs/ca
    networks:
      jenkins:
        aliases:
          - docker
  jenkins:
    #image: jenkins/jenkins:lts
    build:
      context: jenkins
    restart: always
    privileged: true
    user: root
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      jenkins:
volumes:
  jenkins_home:
  jenkins-docker-certs:
networks:
  jenkins:
    driver: bridge
